all:
  hosts:
    web01:
      ansible_host: 172.31.26.204
    web02:
      ansible_host: 172.31.26.205
    web03:
      ansible_host: 172.31.26.206
      ansible_user: ubuntu # using host variable to override the global var value of ec2-user
    db01:
      ansible_host: 172.31.26.206

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: clientkey.pem
