---
- name: Provisioning Servers
  hosts: all
  become: yes
  roles:
    - role: post-install
      vars: # overriding defaults and vars main.yml variables
        ntp0: 0.in.pool.ntp.org
        ntp1: 1.in.pool.ntp.org
        ntp2: 2.in.pool.ntp.org
        ntp3: 3.in.pool.ntp.org
